### ISSUE TITLE
'Long' only refers to a type, but is being used as a namespace here.

### ISSUE THREAD

**Issue by rishikhesh-cyD** [osmosis-labs/osmojs#13]
Long is not imported into the file that throughs error

<img width="553" alt="Screenshot 2022-10-11 at 12 02 24 PM" src="https://user-images.githubusercontent.com/107479292/195014076-5ec4ae0a-dc35-4244-b123-41508790ddbb.png">
<img width="716" alt="Screenshot 2022-10-11 at 12 02 34 PM" src="https://user-images.githubusercontent.com/107479292/195014104-b7de1338-03ad
<img width="510" alt="Screenshot 2022-10-11 at 12 17 32 PM" src="https://user-images.githubusercontent.com/107479292/195016012-3999b1ec-5108-4c1d-9aef-50c8ea21315c.png">

**Comment by pyramation** [comment]
I haven't seen this, but I have seen ts complaining about `import Long from 'long'`. 

Do you have a suggestion for the fix?

**Comment by pyramation** [comment]
or you mean to say that `Long` is never imported?

**Comment by rishikhesh-cyD** [comment]
> or you mean to say that `Long` is never imported?

If I look into the code of that file where i get the error, Long was not imported

**Comment by rishikhesh-cyD** [comment]
> I haven't seen this, but I have seen ts complaining about `import Long from 'long'`.
> 
> Do you have a suggestion for the fix?

Even am looking for the fix

**Comment by pyramation** [comment]
I think I am able to fix if it's just missing an import.

**Comment by rishikhesh-cyD** [comment]
<img width="510" alt="Screenshot 2022-10-11 at 12 17 32 PM" src="https://user-images.githubusercontent.com/107479292/195016575-23a596ca-8d80-4ed8-8dc7-f7cb01b9e046.png">
Also am getting this import error

**Comment by pyramation** [comment]
```js
import { AminoMsg } from "@cosmjs/amino";
import { Long } from "../../../../helpers";
import { MsgCreateStableswapPool, MsgStableSwapAdjustScalingFactors } from "./tx";
export interface AminoMsgCreateStableswapPool extends AminoMsg {
    type: "osmosis/gamm/create-stableswap-pool";
    value: {
        sender: string;
        pool_params: {
            swap_fee: string;
            exit_fee: string;
        };
        initial_pool_liquidity: {
            denom: string;
            amount: string;
        }[];
        scaling_factors: Long[];
        future_pool_governor: string;
    };
}
export interface AminoMsgStableSwapAdjustScalingFactors extends AminoMsg {
    type: "osmosis/gamm/stable-swap-adjust-scaling-factors";
    value: {
        sender: string;
        pool_id: string;
        scaling_factors: Long[];
    };
}
export declare const AminoConverter: {
    "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgCreateStableswapPool": {
        aminoType: string;
        toAmino: ({ sender, poolParams, initialPoolLiquidity, scalingFactors, futurePoolGovernor }: MsgCreateStableswapPool) => AminoMsgCreateStableswapPool["value"];
        fromAmino: ({ sender, pool_params, initial_pool_liquidity, scaling_factors, future_pool_governor }: AminoMsgCreateStableswapPool["value"]) => MsgCreateStableswapPool;
    };
    "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgStableSwapAdjustScalingFactors": {
        aminoType: string;
        toAmino: ({ sender, poolId, scalingFactors }: MsgStableSwapAdjustScalingFactors) => AminoMsgStableSwapAdjustScalingFactors["value"];
        fromAmino: ({ sender, pool_id, scaling_factors }: AminoMsgStableSwapAdjustScalingFactors["value"]) => MsgStableSwapAdjustScalingFactors;
    };
};
```

what version are you running? This all seems to work.

**Comment by rishikhesh-cyD** [comment]
If I use npm i osmojs it installs v0.28.0

**Comment by pyramation** [comment]
and you don't see `import { Long } from "../../../../helpers";` at the top of the files where `Long` is used? I can't seem to find this missing as indicated.

**Comment by rishikhesh-cyD** [comment]
node_modules/osmojs/types/codegen/osmosis/bundle.d.ts:1211:50 - error TS2304: Cannot find name 'Long'.

1211                                 scaling_factors: Long[];
                                                      ~~~~

node_modules/osmojs/types/codegen/osmosis/client.d.ts:589:30 - error TS2304: Cannot find name 'Long'.

589             scaling_factors: Long[];

**Comment by rishikhesh-cyD** [comment]
<img width="768" alt="Screenshot 2022-10-11 at 12 33 45 PM" src="https://user-images.githubusercontent.com/107479292/195018786-bc386243-8514-4e88-ac21-60d02b4b2028.png">
You can see here that there it says import it

**Comment by rishikhesh-cyD** [comment]
> ```js
> import { AminoMsg } from "@cosmjs/amino";
> import { Long } from "../../../../helpers";
> import { MsgCreateStableswapPool, MsgStableSwapAdjustScalingFactors } from "./tx";
> export interface AminoMsgCreateStableswapPool extends AminoMsg {
>     type: "osmosis/gamm/create-stableswap-pool";
>     value: {
>         sender: string;
>         pool_params: {
>             swap_fee: string;
>             exit_fee: string;
>         };
>         initial_pool_liquidity: {
>             denom: string;
>             amount: string;
>         }[];
>         scaling_factors: Long[];
>         future_pool_governor: string;
>     };
> }
> export interface AminoMsgStableSwapAdjustScalingFactors extends AminoMsg {
>     type: "osmosis/gamm/stable-swap-adjust-scaling-factors";
>     value: {
>         sender: string;
>         pool_id: string;
>         scaling_factors: Long[];
>     };
> }
> export declare const AminoConverter: {
>     "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgCreateStableswapPool": {
>         aminoType: string;
>         toAmino: ({ sender, poolParams, initialPoolLiquidity, scalingFactors, futurePoolGovernor }: MsgCreateStableswapPool) => AminoMsgCreateStableswapPool["value"];
>         fromAmino: ({ sender, pool_params, initial_pool_liquidity, scaling_factors, future_pool_governor }: AminoMsgCreateStableswapPool["value"]) => MsgCreateStableswapPool;
>     };
>     "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgStableSwapAdjustScalingFactors": {
>         aminoType: string;
>         toAmino: ({ sender, poolId, scalingFactors }: MsgStableSwapAdjustScalingFactors) => AminoMsgStableSwapAdjustScalingFactors["value"];
>         fromAmino: ({ sender, pool_id, scaling_factors }: AminoMsgStableSwapAdjustScalingFactors["value"]) => MsgStableSwapAdjustScalingFactors;
>     };
> };
> ```
> 
> what version are you running? This all seems to work.

What version should I use

**Comment by pyramation** [comment]
I don't see the issue with long in 0.28. It is exported from the helpers file:

```js
import Long from 'long';

if (_m0.util.Long !== Long) {
    _m0.util.Long = (Long as any);

    _m0.configure();
}

export { Long };
```

**Comment by pyramation** [comment]
I can only see screenshots, but do you see an import at the top of the file? I am starting to think it's an issue with something else besides the code or long type itself. Maybe the TS server.

**Comment by pyramation** [comment]
for long maybe we can try

```js
import * as Long from 'long'; 
```

instead of 

```js
import Long from 'long'
```

and then export it. This may fix that part.

**Comment by rishikhesh-cyD** [comment]
> I can only see screenshots, but do you see an import at the top of the file? I am starting to think it's an issue with something else besides the code or long type itself. Maybe the TS server.

Nope I don't see any import statements for Long in this file node_modules/osmojs/types/codegen/osmosis/client.d.ts

**Comment by pyramation** [comment]
> > I can only see screenshots, but do you see an import at the top of the file? I am starting to think it's an issue with something else besides the code or long type itself. Maybe the TS server.
> 
> Nope I don't see any import statements for Long in this file node_modules/osmojs/types/codegen/osmosis/client.d.ts

ok, that's what I needed, thanks for the path. Will get this taken care of.

**Comment by rishikhesh-cyD** [comment]
> > > I can only see screenshots, but do you see an import at the top of the file? I am starting to think it's an issue with something else besides the code or long type itself. Maybe the TS server.
> > 
> > 
> > Nope I don't see any import statements for Long in this file node_modules/osmojs/types/codegen/osmosis/client.d.ts
> 
> ok, that's what I needed, thanks for the path. Will get this taken care of.

Thanks for looking into it, let me know if the issue is fixed

**Comment by pyramation** [comment]
```
Successfully published:
 - osmojs@0.29.0
```

**Comment by pyramation** [comment]
should be fixed now @rishikhesh-cyD

**Comment by pyramation** [comment]
- [x] this file is now created: https://github.com/osmosis-labs/osmojs/blob/fbfcbab095397bdf4dc49e05007530ddb9bedc1b/packages/osmojs/types/codegen/osmosis/streamswap/v1/tx.rpc.msg.d.ts#L39
- [x] `long` is now imported: https://github.com/osmosis-labs/osmojs/blob/fbfcbab095397bdf4dc49e05007530ddb9bedc1b/packages/osmojs/types/codegen/osmosis/client.d.ts#L589

**Comment by rishikhesh-cyD** [comment]
@pyramation still facing some issues with the long import 
<img width="519" alt="Screenshot 2022-10-11 at 1 29 20 PM" src="https://user-images.githubusercontent.com/107479292/195032716-a4ffeac7-c010-4c96-8de7-b8454e73a9b9.png">
